name: Foerderportal data import

on:
  push:
    paths:
      - .github/workflows/foerderportal.yml
  workflow_dispatch: #empty for now
  schedule:
    - cron: '30 5 * * 1,3'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Fetch data
        env:
          SESSIONID: ${{ secrets.SESSION_ID }}
        run: |
          curl --cookie JSESSIONID=$SESSIONID -o foerderportal.csv https://foerderportal.bund.de/foekat/jsp/SucheAction.do\?actionMode\=print\&presentationType\=csv
          head -n 5 foerderportal.csv
      - uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          email: ${{ github.actor }}@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: update foerderportal.csv
          files: foerderportal.csv