name: Foerderportal data import

on:
  push:
    paths:
      - .github/workflows/foerderportal.yml
  workflow_dispatch: #empty for now
  schedule:
    - cron: '30 5 * * 1,3'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          # http_url: https://foerderportal.bund.de/foekat/jsp/SucheAction.do?actionMode=print&presentationType=csv
          http_url: https://cordis.europa.eu/data/cordis-h2020projects-csv.zip
          downloaded_filename: foerderportal.zip
          axios_config: foerderportal_config.json
