name: Foerderportal data import

on:
  push:
    paths:
      - .github/workflows/foerderportal.yml
  workflow_dispatch: #empty for now
  schedule:
    - cron: '30 5 * * 1,3'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Fetch data
        env:
          SESSIONID: ${{ secrets.SESSION_ID }}
        run: |
          curl --cookie JSESSIONID=$SESSIONID -o foerderportal.csv https://foerderportal.bund.de/foekat/jsp/SucheAction.do\?actionMode\=print\&presentationType\=csv
          tail -100 foerderportal.csv > foerderportal_newest_100.csv
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add foerderportal_newest_100.csv
          timestamp=$(date -u)
          git commit -m "data(foederportal): ${timestamp}" || exit 0
          git push
