name: Foerderportal data import

on:
  push:
    paths:
      - .github/workflows/foerderportal.yml
  workflow_dispatch: #empty for now
  schedule:
    - cron: '30 5 * * 1,3'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Fetch data
        run: |
          curl -s --cookie-jar cookies.txt https://foerderportal.bund.de/foekat/jsp/SucheAction.do?actionMode=searchreset >/dev/null 2>&1
          curl --cookie cookies.txt -o foerderportal.csv https://foerderportal.bund.de/foekat/jsp/SucheAction.do?actionMode=print&presentationType=csv
      - uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          email: ${{ github.actor }}@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: update foerderportal.csv
          files: foerderportal.csv