name: H2020 CORDIS data import

on:
  push:
    paths:
      - .github/workflows/h2020.yml
  workflow_dispatch: #empty for now
  schedule:
    - cron: '30 5 * * 1,3'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Fetch data
        run: |-
          curl -o h2020_data.zip https://cordis.europa.eu/data/cordis-h2020projects-csv.zip
          unzip h2020_data.zip
          mv csv/project.csv h2020_projects.csv
          mv csv/organization.csv h2020_organizations.csv
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add h2020_organizations.csv h2020_projects.csv
          timestamp=$(date -u)
          git commit -m "Latest h2020 data: ${timestamp}" || exit 0
          git push
