name: H2020 CORDIS data import

on:
  push:
    paths:
      - .github/workflows/h2020.yml
  workflow_dispatch: #empty for now
  schedule:
    - cron: '30 5 * * 1,3'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Fetch data
        run: |
          curl -o h2020_projects.zip https://cordis.europa.eu/data/cordis-h2020projects-csv.zip
          unzip h2020_projects.zip
          tail -500 cordis-h2020projects.csv > h2020_projects_newest_500.csv
      - uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          email: ${{ github.actor }}@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: update h2020_projects.csv
          files: h2020_projects_newest_500.csv
