name: H2020 CORDIS data import

on:
  push:
    paths:
      - .github/workflows/h2020.yml
  workflow_dispatch: #empty for now
  schedule:
    - cron: '30 5 * * 1,3'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://cordis.europa.eu/data/cordis-h2020projects-csv.zip
          downloaded_filename: h2020.zip
