name: Aura DB Util Job

on:
  push:
    paths:
      - .github/workflows/utility.yml
      - aura_util.cypher
  workflow_dispatch: #empty for now

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Prevent_Idle
        uses: cbastn/cypher-shell-docker@v1
        with:
          address: ${{ secrets.NEO4J_URI }}
          username: ${{ secrets.NEO4J_USER }}
          password: ${{ secrets.NEO4J_PASSWORD }}
          file: "aura_util.cypher"
